### ISSUE TITLE
"No files here" although files exist

### ISSUE THREAD

**Issue by working-name** [nextcloud/android#10686]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Install latest nextcloud in docker, have it reverse proxied by nginx
2. place some files in your user's home directory
3. install nextcloud client on android and open it.
4. You'll get "No files here", but you can see some media files

### Expected behaviour

Show the files.

### Actual behaviour

"No files here" is displayed which is a fat lie.

### Android version

12

### Device brand and model

galaxy tab s7+

### Stock or custom OS?

Stock

### Nextcloud android app version

20220827 (debug version) or 3.21.1

### Nextcloud server version

24.0.4

### Using a reverse proxy?

Yes

### Android logs

Not a rooted device, and logcat doesn't spit anything out (your instructions are outdated anyway but found the pid via `ps -fl`

### Server error logs

```bash
Error	no app in context	OCP\AppFramework\QueryException: Could not resolve logger! Class "logger" does not exist		10 minutes ago
Error	no app in context	OCP\AppFramework\QueryException: Could not resolve logger! Class "logger" does not exist		an hour ago
Error	no app in context	OCP\AppFramework\QueryException: Could not resolve logger! Class "logger" does not exist		an hour ago
Error	no app in context	OCP\AppFramework\QueryException: Could not resolve logger! Class "logger" does not exist		an hour ago
Error	no app in context	OCP\AppFramework\QueryException: Could not resolve logger! Class "logger" does not exist		an hour ago
Error	no app in context	OCP\AppFramework\QueryException: Could not resolve logger! Class "logger" does not exist
```

### Additional information

Getting to the bottom of this has been extremely frustrating. If there's a problem just spit it out in an **user-accessible** location on android. Or provide a share option for the logfile when stuff happens. How does one get to emulated/storage/0 on a non-rooted device? And then having to run adb logcat and other such oddities is just beyond me. Last time I got angry with Nextcloud and ignored it for years I was running the app manually, on my own nginx-php stack, so this time around I thought maybe give the docker image a try. That one can't even find its logger class. 🤦 I don't know what to say, I'm beyond disappointed in how difficult you're making it to figure out what is the problem.

And here's some more fun info: iOS is able to access the user's files both from the iOS file manager and the nextcloud client app itself.

**Comment by AlvaroBrey** [comment]
Nothing I can say here without logs, as I can't reproduce it.  Can you post a reproducible setup? a docker-compose file would be ideal.

> Not a rooted device, and logcat doesn't spit anything out (your instructions are outdated anyway but found the pid via ps -fl

There should be logs in logcat in any version. Additionally in the debug version you should be able to see/share them via Settings, with no need for ADB.

**Comment by working-name** [comment]
I was so annoyed with logcat not spitting anything I didn't even think to check settings. My apologies. Here's the log for the initial list of root folder on app open: [nextcloud-logs.txt](https://github.com/nextcloud/android/files/9454562/nextcloud-logs.txt)

### compose file
```YAML
version: "3"

services:
  nextcloud:
    image: nextcloud:latest
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=ncmofo
      - MYSQL_PASSWORD=clipidogrel-several-nonskid-infarctions-cull
      - TZ=America/New_York
      - VIRTUAL_HOST= nextclouddomain.com
      #- TRUSTED_PROXIES=10.0.0.190
      - SMTP_HOST=e.maildomain.com
      - SMTP_SECURE=ssl
      - SMTP_PORT=465
      - SMTP_NAME=my@maildomain.com
      - SMTP_PASSWORD=---xx--XX--XXX-
      #- MAIL_FROM_ADDRESS=
      - MAIL_DOMAIN=maildomain.com
      - PHP_UPLOAD_LIMIT=2048M
    volumes:
      - nextcloud:/var/www/html

  mysql:
    image: mariadb:latest
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=ncmofo
      - MYSQL_PASSWORD=clipidogrel-several-nonskid-infarctions-cull
      - MYSQL_ROOT_PASSWORD=rapper-bess-laymen-musculocutaneous-booking-rim
      - TZ=America/New_York
    volumes:
      - nextcloudmariadb:/var/lib/mysql



volumes:
  nextcloudmariadb:
  nextcloud:
```

The only logs I see coming out from the docker setup is apache's access logs - useless.

Then of course, NC itself doesn't log much other than the occasional "can't find my logger class" which I pasted above.

Hope this helps point me in the right direction.
