### ISSUE TITLE
Can't login into Nextcloud 18.0.3

### ISSUE THREAD

**Issue by QuAzI** [nextcloud/android#5865]
### Steps to reproduce
1. Self-hosted Nextcloud 18.0.3 installed (docker image + MariaDB)
2. Run Nextcloud or Nextcloud talks from Google Play
3. Enter server address, login, pass
4. Press "Grant access"

### Actual behavior
Nothing happens. App frozen.
![photo_2020-04-14_09-50-45](https://user-images.githubusercontent.com/1897605/79194588-82243980-7e35-11ea-8948-fe94f864e918.jpg)

But auth records created
![20200414_095336](https://user-images.githubusercontent.com/1897605/79194809-e515d080-7e35-11ea-92d1-261d61f1e9c1.png)

All works for browser or WebDAV but not for official mobile apps.

### Can you reproduce this problem on https://try.nextcloud.com?
All works with demo server

### Environment data
Android version: 10
Device model: Samsung Note10+ SM-N9750
Stock or customized system: Stock
Nextcloud app version: 3.11
Nextcloud server version: 18.0.3

### docker-compose
```
version: '3.0'

services:
    nextcloud:
        image: nextcloud
        volumes:
            - ./nextcloud:/var/www/html
            - ./data:/var/www/html/data
        links:
            - db
        restart: always

    db:
        image: mariadb
        command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
        volumes:
            - ./db:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=<pass>
            - MYSQL_PASSWORD=<pass>
            - MYSQL_DATABASE=nextcloud
            - MYSQL_USER=nextcloud
        restart: always
```
